#端口号
server:
  port: 8080

#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#当mapper接口和mapper和mapper接口对应的配置文件名称和路径不一样时(比如BookDao和BookMapper.xml)，需要配置mapper-locations绑定位置
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: com.itheima.mybatis_plus_generator.entity #实体类位置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql执行语句到控制台
  global-config:
    db-config:
      id-type: auto

#当mapper接口和mapper和mapper接口对应的配置文件名称和路径不一样时(比如BookDao和BookMapper.xml)，需要配置mapper-locations绑定位置
#mybatis:
#  mapper-locations: classpath:mapper/xml/*.xml
#  type-aliases-package: com.itheima.mybatis_plus_generator.entity #实体类位置
#  configuration:
#    map-underscore-to-camel-case: true

#设置日志模板格式
logging:
  file:
    name: server.log     #命名输出日志文件
  logback:
    rolling policy:
      max-file-size: 10MB   #设置日志最大容量
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log #日志文件命名规则

