#端口号
server:
  port: 8080

#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#当mapper接口和mapper和mapper接口对应的配置文件名称和路径不一样时(比如BookDao和BookMapper.xml)，需要配置mapper-locations绑定位置
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: com.itheima.mybatis_plus_generator.entity #实体类位置
  configuration:
    map-underscore-to-camel-case: true

#当mapper接口和mapper和mapper接口对应的配置文件名称和路径不一样时(比如BookDao和BookMapper.xml)，需要配置mapper-locations绑定位置
#mybatis:
#  mapper-locations: classpath:mapper/xml/*.xml
#  type-aliases-package: com.itheima.mybatis_plus_generator.entity #实体类位置
#  configuration:
#    map-underscore-to-camel-case: true

